version: 2
defaults: &defaults
  machine: true


jobs:
  build_amd64:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build image for amd64
          command: make ARCH=amd64
      - deploy:
          name: Push image for amd64 to dockerhub
          command: docker login -u "$DOCKERHUB_USER" -p $DOCKERHUB_PASS && make ARCH=amd64 push
  
  build_arm32v6:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build image for arm32v6
          command: make ARCH=arm32v6
      - deploy:
          name: Push image for arm32v6 to dockerhub
          command: docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS" && make ARCH=arm32v6 push


  build_arm64v8:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build image for arm64v8
          command: make ARCH=arm64v8
      - deploy:
          name: Push image for arm64v8 to dockerhub
          command: docker login -u "$DOCKERHUB_USER" -p $DOCKERHUB_PASS && make ARCH=arm64v8 push


  manifest:
    <<: *defaults
    steps:
      - checkout
      - deploy:
          name: Generate multiarch manifest and push to dockerhub
          command: docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS" && make manifest


          
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_amd64
      - build_arm32v6
      - build_arm64v8
      - manifest:
          requires:
            - build_amd64
            - build_arm32v6
            - build_arm64v8
